### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zc1108aaa** [Cam11062/Strange-Berries#10] opened 2024-06-02 04:05 UTC
[latest.log](https://github.com/user-attachments/files/15524119/latest.log)

**Comment by reiieva** [comment] 2024-06-02 21:17
Hi there! The log file you have attached does not reference Strange Berries as causing the error in your Minecraft instance.

Your error seems to be an issue with the mod "Tiny Allies" as seen in the line: `Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [tinyallies-common.mixins.json:ZombieMixin from mod tinyallies] from phase [DEFAULT] in config [tinyallies-common.mixins.json] FAILED during APPLY`

I recommend that you either remove the mod, change the version of the mod, or contact the developer of said mod. 

Anyways, I'm going to close the issue as this isn't related to Strange Berries.

Hope this helps!
Cameron

**Closed as completed by reiieva** 2024-06-02 21:17 UTC
Labels: invalid
